addons:
    postgresql: "9.3"

language: python

python:
  - "2.7"

env:
  - DJANGO=Django==1.6.11

install:
  - pip install -q $DJANGO

before_script:
    - psql -U postgres -c "create database jmbo encoding 'UTF8'"

script: python setup.py test
