addons:
    postgresql: "9.1"

language: python

python:
  - "2.7"

env:
  - DJANGO=Django==1.4.10

install:
  - pip install -q $DJANGO
  - pip install -r poll/tests/requirements.txt

before_script:
    - psql -U postgres -c "create database jmbo encoding 'UTF8'"

script: python setup.py test
